twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
        language_context: '@App\Core\Language\LanguageContext'
    form_themes: ['bootstrap_4_layout.html.twig']